env:
  global:
    - # BINTRAY_USER
    - secure: e5RWZftAQduH8gZwr2WmOJp9eHQ4euEccDQMkWRTIS1LpyxJRKL8lXufv+EvrHIE2+zJ0Cr6ag7bVi+NFUDDQIwT+x5goJ/RfMkC6607DvviZnidSZ9OxX3BVE0b9O78A4BZSFgdj30HcfxvjXxZG9FtCXVJtCR52bvbMAT0C2q3aQc1fT8cuY85NrufXLaAAHzv80DbgF7QQ538qi9M8NCcJTcbF8fgDgPRmNBrRqqjY5JHxS+knSRRvuxkOMj48yLO90ECCVXXxcUkEfZqwWYZP/ZyPLotRyhHgPcoLpwCkKCzB8iXyjnv/5GCEG32Np5Ds7jgFIsQkaxb4ZAbEx/k3Caycw8wrVUPKXRHOYokIm7O1TDzqxdcWlkrDAaInXHdVGhENMnhO8u7cSOkGQbVhw8gEFJHKLXooYHbANB4EizK5CH0Z+eRFA00CnPNGltNbZif29kiCDOh8tiz3HhCYYgo7p3gGKJWb/BAuzr+hGK2IhXRkqJW9nQFxcCFRYZyQBPOPOP9Yn0wMpTkGjjAATnO1xZUjO5nXyEMGx5sDiNhZs4Zy/Tqcz5cwx6NGSAPkEjRbNubPzZ4elP05QR/qdrs71rYQ2URMiUFo3CvAu3z8snMpdMxQcheqXlfEfGGeugTZi4MNXvVsgbYQ8/bAuCtfheY9u7w9RFy4WQ=
    - # BINTRAY_API_KEY
    - secure: HIZXYItgPxsYDTOQFFaAzxWtEH0DBc/IAGaB2ukrsH9Ix6nymJGZa5wNN6OtMapbi99Kd9Q6b1bkIjtEFlcALEektLiGRgWMsOe2A7Kix6O6ahnI5K76Tb8BoYdJKkcZQ5zN2tqFeyOntKP5w/4kacZ4LokxudOUgzoi4d5JN06JdnAB1RmAZ6DTW1grFwTWmsE/jFp5PMTjZ3MukD3dPsG2gsJ6Y5ymkGbbNMnQzf4zgEG8JfmhTdLi9io5kLN+LqzvpMwc1OlRSsreoxjh5IvP6I3CSK+LIRemFBHwssiJ1zjC+uTvwe8AJ2ZDCNukv+RnXutAih2Eq/7ZcYmir6KeL7AMDG7KFWgFBZ+gZjIWnbcfaRr0zf5TkXM61P/0wYLFQJNEQwleRwB4SfzbfSKEbdDEbwPzEHUdQoFKa9QT85Vg1QA9o13d0ylcxUp0oh5ZDTzd+mob99ftHbFwqsDqU6By8OPfwYy+eVCNOf2PESv6lGVQN7/yZ6io9kf5jQDrRJSuhPcmutVEKk+DEMNyXq1olUbiz77feS5wWsx7S4l4laVOyJIp8CfkmA3kXlihaGHyOZKErnKxw6JqUhZCUTeAa27IV/3d+N2BVHNizcGHQ6R5NRfPVlPw1fprL16bKEJlHkAlyK835KqvJGFuqFXuq4eydM2O2Lj6Iz4=

dist: trusty
language: java
jdk:
  - openjdk12
script:
  - chmod -R ug+x .ci
  - .ci/build.sh
  - .ci/publish.sh
